var ron1_steps=new Array("acetazolamide","Diamox","antiglaucoma/carbonic anhydrase inhibitor",
"acyclovir","Zovirax","antiviral",
"alendronate","Fosamax","anti-osteoporosis/bisphosphonates",
"allopurinol","Zyloprim","antigout",
"Al-Mg-simethicone","Maalox","antacid",
"Al-Mg-simethicone","Gelusil","antacid",
"Al-Mg-simethicone","Mylanta","antacid",
"aluminum hydroxide gel","AlternaGel","antacid",
"alprazolam","Xanax, XR","ST anti-anxiety/benzodiazepine",
"amantadine","Symmetrel","parkinsons/antiviral",
"amitriptyline","Elavil","antidepressant/tricyclic",
"amphetamine","Adderall, XR","ADHD stimulant",
"anastrozole","Arimidex","anticancer/anti-estrogen",
"aripiprazole","Abilify","atypical (2) antipsychotic",
"atomoxetine","Strattera","noncontrolled ADHD nonstimulant",
"atropine","atropine","anti-cholinergic",
"atropine","Isopto Atropine","mydriatic",
"baclofen","Lioresal","skeletal muscle relaxant",
"benzocaine","Lanacaine","antipruritic/antihistamine",
"benzocaine","Americaine","antipruritic/antihistamine",
"benzocaine","Orajel","antipruritic/antihistamine",
"benzoyl peroxide","Benzac","acne",
"benzoyl peroxide","Desquam-X","acne",
"benzoyl peroxide","Panoxyl-5 and 10","acne",
"benztropine","Cogentin","parkinsons/anticholinergic",
"betaxolol","Betoptic-S","antiglaucoma/beta-adrenergic blocker",
"bethanechol","Urecholine","cholinergic",
"bevacizumab","Avastin","anticancer/MAB",
"bicalutamide","Casodex","anticancer/anti-androgen",
"bisacodyl","Dulcolax","stimulant laxative",
"bisacodyl","Fleet","stimulant laxative",
"bismuth subsalicylate","Kaopectate","antidiarrheal",
"bismuth subsalicylate","Pepto-Bismol","antidiarrheal",
"bleomycin","Blenoxane","anticancer/antitumor antibiotic",
"brimonidine","Alphagan-P","antiglaucoma/alpha agonist",
"bromocriptine","Parlodel","parkinsons/dopamine agonist",
"bumetanide","Bumex","loop diuretic",
"bupropion","Wellbutrin, SR, XL","antidepressant/heterocyclic",
"buspirone","Buspar","anti-anxiety",
"caffeine citrate","Cafcit","stimulant",
"calcitonin-salmon","Miacalcin","anti-osteoporosis",
"calcium carbonate","Tums","antacid",
"carbamazepine","Tegretol, XR","antimanic/anticonvulsant (1)",
"carbidopa and levodopa","Sinemet, CR","parkinsons/dopamine replacement",
"carbidopa and levodopa","Parcopa","parkinsons/dopamine replacement",
"carisoprodol","Soma","C4 skeletal muscle relaxant",
"celecoxib","Celebrex","selective COX-2 inhibitor",
"chlordiazepoxide","Librium","ST anti-anxiety/benzodiazepine",
"chlorhexidine","Hibiclens","topical anti-infective/antiseptic",
"chlorhexidine","Peridex","topical anti-infective/antiseptic",
"chlorpromazine","Thorazine","typical (1) antipsychotic/phenothiazine",
"cimetidine","Tagamet","histamine 2 blocker",
"cisplatin","Platinol","anticancer/alkylating agent",
"citalopram","Celexa","antidepressant/SSRI",
"clonazepam","Klonopin","anticonvulsant (1)",
"clorazepate","Tranxene","ST anti-anxiety/benzodiazepine",
"clotrimazole","Lotrimin, Gyne-","antifungal",
"clozapine","Clozaril","atypical (2) antipsychotic",
"clozapine","Fazaclo ODT","atypical (2) antipsychotic",
"coal tar","Balnetar","keratolytic",
"coal tar","Polytar","keratolytic",
"coal tar","Neutrogena T/Gel","keratolytic",
"colchicine","Colcrys","antigout",
"collagenase","Santyl","enzymatic",
"cortisol","Cortaid","antipruritic/corticosteroid",
"cyclobenzaprine","Flexeril","skeletal muscle relaxant",
"cyclopentolate","Cyclogyl","mydriatic",
"cyclophosphamide","Cytoxan","anticancer/alkylating agent",
"cyclosporine","Restasis","anti-inflammation/immunologic agent",
"dantrolene","Dantrium","skeletal muscle relaxant",
"darifenacin","Enablex","antispasmodic",
"daunorubicin","Cerubidne","anticancer/antitumor antibiotic",
"desipramine","Norpramin","antidepressant/tricyclic",
"desoximetasone","Topicort","antipruritic/corticosteroid",
"desvenlafaxine","Pristiq","antidepressant/SNRI",
"dexamethasone","Decadron","anticancer/corticosteroid",
"dexamethasone","Maxidex","NSAID",
"diazepam","Valium","ST anti-anxiety/benzodiazepine/C4 skeletal muscle relaxant",
"diazepam","Diastat","ST anti-anxiety/benzodiazepine/C4 skeletal muscle relaxant",
"dibucaine","Nupercainal","antipruritic/antihistamine",
"diclofenac","Voltaren DR, XR","nonselective/traditional NSAID",
"diclofenac/misoprostol","Arthrotec 50, 75","antispasmodic",
"dicyclomine","Bentyl","antispasmodic/anticholinergic",
"dimenhydrinate","Dramamine","anti-emetic/anticholinergic",
"diphenhydramine","Benadryl","antipruritic/antihistamine",
"diphenoxylate/atropine","Lomotil","antidiarrheal/anticholinergic",
"docusate","Colace","laxative/stool softener",
"dolasetron","Anzemet","anti-emetic/serotonin receptor antagonist",
"donepezil","Aricept, ODT","alzheimers/cholinesterase inhibitor",
"dopamine","dopamine","adrenergic",
"dorzolamide","Trusopt","antiglaucoma/carbonic anhydrase inhibitor",
"doxazosin","Cardura","BPH alpha-blocker",
"doxepin","Sinequan","antidepressant/tricyclic",
"doxorubicin","Adriamycin","anticancer/antitumor antibiotic",
"duloxetine","Cymbalta","antidepressant/SNRI",
"dutasteride","Avodart","BPH anti-androgen",
"entacapone","Comtan","parkinsons/COMT inhibitor",
"entacapone c carbidopa/levodopa","Stalevo","parkinsons/COMT inhibitor",
"ephedrine","ephedrine","adrenergic",
"epinephrine","Adrenalin","adrenergic",
"epinephrine","EpiPen, Jr","adrenergic",
"escitalopram","Lexapro","antidepressant/SSRI",
"esomeprazole","Nexium","PPI ac",
"ethosuximide","Zarontin","anticonvulsant (1)",
"etodolac","Lodine","partially selective NSAID",
"famotidine","Pepcid","histamine 2 blocker",
"finasteride","Proscar","BPH anti-androgen",
"fluocinolone acetonide","Synalar","antipruritic/corticosteroid",
"fluocinonide","Lidex","antipruritic/corticosteroid",
"fluorometholone","FML","anti-inflammation/corticosteroid",
"fluorouracil","Efudex","anticancer/antimetabolite",
"fluoxetine","Prozac","antidepressant/SSRI",
"fluphenazine","Prolixin","typical (1) antipsychotic/phenothiazine",
"flurbiprofen","Ocufen","NSAID",
"fosphenytonin","Cerebyx","anticonvulsant (1)",
"furosemide","Lasix","loop diuretic",
"gabapentin","Neurontin","anticonvulsant (2)",
"pregablin","Lyrica","anticonvulsant (2)",
"galantamine","Razadyne, ER","alzheimers/cholinesterase inhibitor",
"glycerine","Colace suppository","osmotic laxative",
"glycopyrrolate","Robinul","anti-cholinergic",
"haloperidol","Haldol, decanoate IM","typical (1) antipsychotic/tranquilizer",
"homatropine","Isopto Homatropine","anti-cholinergic",
"hydrochlorothiazide","Microzide","thiazide diuretic",
"hydrocortisone","Cortel","glucocorticoid",
"hydroxyzine","Vistaril","anti-anxiety",
"hyoscyamine","Cystospaz","antispasmodic",
"hyoscyamine","Levsin","antispasmodic",
"ibandronate","Boniva","anti-osteoporosis/bisphosphonates",
"ibuprofen","Motrin","nonselective/traditional NSAID",
"ibuprofen","Advil (OTC)","nonselective/traditional NSAID",
"imipramine","Tofranil","antidepressant/tricyclic",
"indapamide","Lozol","thiazide diuretic",
"indomethacin","Indocin, SR","nonselective/traditional NSAID",
"interferon alfa","Intron A","anticancer/interferon",
"interferon alfa","Roferon B","anticancer/interferon",
"isocarboxazid","Marplan","antidepressant/MAOI",
"isoproterenol","Isuprel","adrenergic",
"isotretinoin","Sotret","acne",
"ketoconazole","Nizoral","antifungal",
"ketorolac","Acular, LS","NSAID",
"ketorolac","Toradol","nonselective/traditional NSAID",
"lactobacillus acidophilus","Lactinex","antidiarrheal/probiotic",
"lactulose","Enulose","osmotic laxative",
"lamotrigine","Lamictal","anticonvulsant (2)",
"lansoprazole","Prevacid","PPI ac",
"latanoprost","Xalatan","antiglaucoma/prostaglandin analog",
"leuprolide acetate","Lupron Depot","anticancer/anti-androgen",
"levetriacetam","Keppra","anticonvulsant (2)",
"lindane","lindane","scabicide/pediculicide",
"lisdexamfetamine","Vyvanse","ADHD stimulant",
"lithium","Lithobid","antimanic",
"lithium","Eskalith","antimanic",
"loperamide","Imodium","antidiarrheal",
"lorazepam","Ativan","ST anti-anxiety/benzodiazepine",
"lubiprostone","Amitiza","laxative/chloride channel activator",
"mafenide","Sulfamylon","burn",
"magnesium hydroxide","Milk of Magnesia","saline laxative",
"mannitol","Osmitrol","osmotic diuretic",
"meclizine","Antivert","anti-emetic/anticholinergic",
"meloxicam","Mobic","partially selective NSAID",
"memantine","Namenda","alzheimers/NMDA-R antagonist",
"mesalamine","Asacol","salicylates",
"mesalamine","Rowasa","salicylates",
"methocarbamol","Robaxin","skeletal muscle relaxant",
"methotrexate","Rheumatrex","anticancer/antimetabolite",
"methylphenidate","Ritalin, SR, LA","narcolepsy/ADHD stimulant",
"methylphenidate","Concerta","narcolepsy/ADHD stimulant",
"methylphenidate","Daytrana Patch","narcolepsy/ADHD stimulant",
"methylphenidate","Metadate ER","ADHD, senile apathy, refractory depression stimulant",
"metoclopramide","Reglan","anti-emetic/antidopaminergic",
"metolazone","Zaroxolyn","thiazide diuretic",
"miconazole","Monistat","antifungal",
"miconazole","Lotrimin AF","antifungal",
"midazolam","Versed","ST anti-anxiety/benzodiazepine",
"mineral oil","Fleet Mineral Oil","laxative/emollient",
"mirtazapine","Remeron","antidepressant/heterocyclic",
"misoprostol","Cytotec","gastric mucosal agent with food",
"mitomycin","Mutamycin","anticancer/antitumor antibiotic",
"modafinil","Provigil","narcolepsy, sleep apnea, shift-work sleep disorder stimulant",
"mupirocin","Bactroban","antibacterial",
"nabumetone","Relafen","partially selective NSAID",
"naproxen","Naprosyn","nonselective/traditional NSAID",
"naproxen","Anaprox","nonselective/traditional NSAID",
"naproxen","Aleve (OTC)","nonselective/traditional NSAID",
"neostigmine","Prostigmin","cholinergic",
"norepinephrine","Levophed","adrenergic",
"nortriptyline","Pamelor","antidepressant/tricyclic",
"nystatin","Mycostatin","antifungal",
"olanzpine","Zyprexa, -Zydis","atypical (2) antipsychotic",
"olanzpine/fluoxetine","Symbyax","antimanic/bipolar depression",
"omeprazole","Prilosec","PPI ac",
"ondansetron","Zofran","anti-emetic/serotonin receptor antagonist",
"oxaprozin","Daypro","nonselective/traditional NSAID",
"oxazepam","Serax","ST anti-anxiety/benzodiazepine",
"oxybutynin","Ditropan, XL","antispasmodic",
"oxybutynin","Oxytrol patch","antispasmodic",
"paclitaxel","Taxol","anticancer/mitotic inibitor/taxane",
"paliperidone","Invega","atypical (2) antipsychotic",
"pantoprazole","Protonix","PPI",
"paroxetine","Paxil, CR","antidepressant/SSRI",
"permethrin","Acticin","scabicide/pediculicide",
"permethrin","Elimite","scabicide/pediculicide",
"permethrin","Nix","scabicide/pediculicide",
"permethrin","A-200","scabicide/pediculicide",
"permethrin","RID","scabicide/pediculicide",
"perphenazine","Trilafon","typical (1) antipsychotic/phenothiazine",
"phenazopyridine","Pyridium","UTI analgesic",
"phenazopyridine","Azo Standard","UTI analgesic",
"phenelzine","Nardil","antidepressant/MAOI",
"phenylephrine","Neo-Synephrine","adrenergic",
"phenylephrine","AK-Dilate","mydriatic",
"phenytoin","Dilantin","anticonvulsant (1)",
"pilocarpine","Isopto Carpine","cholinergic",
"pilocarpine gel","Pilopine HS","antiglaucoma/miotic",
"pilocarpine HCl","Isopto Carpine","antiglaucoma/miotic",
"polyethylene glycol","Miralax","osmotic laxative",
"povidone-iodine","Betadine","topical anti-infective/antiseptic",
"pramipexole","Mirapex","parkinsons/dopamine agonist",
"prednisolone","Medrol","glucocorticoid",
"prednisolone","Omnipred","anti-inflammation/corticosteroid",
"prednisolone","Pred Forte","anti-inflammation/corticosteroid",
"prednisone","Deltasone","anticancer/corticosteroid/glucocorticoid",
"probenecid","Benemid","uricosuric agent",
"prochlorperazine","Compazine","typical (1) antipsychotic/phenothiazine/anti-emetic/antidopaminergic",
"promethazine","Phenergan","anti-emetic/antidopaminergic",
"propantheline","Pro-Banthine","anti-cholinergic",
"proparacaine","Alcaine","local anesthetic",
"propranolol","Inderal","anti-adrenergic",
"psyllium","Metamucil","bulk-forming laxative",
"psyllium","Konsyl-D","bulk-forming laxative",
"psyllium","Hyrocil","bulk-forming laxative",
"pyrethrins","RID","scabicide/pediculicide",
"pyrethrins","A-200","scabicide/pediculicide",
"quetiapine","Seroquel, XR","atypical (2) antipsychotic",
"rabeprazole","Aciphex","PPI",
"raloxifene","Evista","anti-osteoporosis/estrogen-R modifier",
"ranitidine","Zantac","histamine 2 blocker",
"rasagiline","Azilect","parkinsons/MAOB inhibitor",
"risedronate","Actonel","anti-osteoporosis/bisphosphonates",
"risperidone","Risperdal","atypical (2) antipsychotic",
"risperidone","Consta","atypical (2) antipsychotic",
"rivastigmine","Exelon","alzheimers/cholinesterase inhibitor",
"ropinirole","Requip","parkinsons/dopamine agonist",
"saccharomyces boulardii","Florastor","antidiarrheal/probiotic",
"salicylic acid","Neutrogena","acne",
"salicylic acid","Clearasil","keratolytic/acne",
"salicylic acid","Salex","keratolytic",
"salicylic acid","Compound W","keratolytic",
"scopolamine","Transderm-Scop","anti-emetic/anti-cholinergic",
"selegiline","Eldepryl","parkinsons/MAOB inhibitor",
"selegiline","Zelapar","parkinsons/MAOB inhibitor",
"senna","Senokot","stimulant laxative",
"senna/docusate","Peri-Colace","stimulant laxative",
"senna/docusate","Senokot-S","stimulant laxative",
"sertraline","Zoloft","antidepressant/SSRI",
"silver sulfadiazine","Silvadene","burn",
"simethicone","Mylicon","antiflatulent",
"solifenacin","VESIcare","antispasmodic",
"sorbitol","sorbitol","osmotic laxative",
"spironolactone","Aldactone","K-sparing diuretic",
"spironolactone/hydrochlorothiazide","Aldactazide","K-sparing thiazide diuretic",
"sucralfate","Carafate","gastric mucosal agent",
"sulfasalazine","Azulfidine","salicylates",
"sulindac","Clinoril","nonselective/traditional NSAID",
"tacrine","Cognex","alzheimers/cholinesterase inhibitor",
"tamoxifen","Nolvadex","anticancer/anti-estrogen",
"tamsulosin","Flomax","BPH alpha-blocker",
"terazosin","Hytrin","BPH alpha-blocker",
"terbinafine","Lamisil, AT","antifungal",
"terbinafine","Mycelex","antifungal",
"teriparatide","Forteo","anti-osteoporosis/parathyroid hormone",
"tetracaine","TetraVisc","local anesthetic",
"thioridazine","Mellaril","typical (1) antipsychotic/phenothiazine",
"thiothixene","Navane","typical (1) antipsychotic",
"timolol","Timoptic, XE","antiglaucoma/beta-adrenergic blocker",
"timolol c dorzolamide","Cosopt","antiglaucoma/beta-adrenergic blocker",
"tizanidine","Zanaflex","skeletal muscle relaxant",
"tolnaftate","Tinactin","antifungal",
"tolterodine","Detrol, LA","antispasmodic",
"topiramate","Topamax","anticonvulsant (2)",
"torsemide","Demadex","loop diuretic",
"tositumomab","Bexxar","anticancer/radioactive isotope",
"tranylcypromine","Parnate","antidepressant/MAOI",
"trastuzumab","Herceptin","anticancer/MAB",
"travoprost","Travatan, -Z","antiglaucoma/prostaglandin analog",
"trazodone","Desyrel","antidepressant/heterocyclic",
"triamcinolone","Kenalog","antipruritic/corticosteroid",
"triamterene","Dyrenium","K-sparing diuretic",
"triamterene/hydrochlorothiazide","Dyazide, Maxzide","K-sparing thiazide diuretic",
"trifluoperazine","Stelazine","typical (1) antipsychotic/phenothiazine",
"trihexyphenidyl","Artane","parkinsons/anticholinergic",
"valacyclovir","Valtrex","antiviral",
"valproate","Depakote, Depakene, ER","antimanic",
"valproic acid","Depakene, Depakote DR, ER, Depacon","anticonvulsant (1)",
"venlafaxine","Effexor, XR","antidepressant/SNRI",
"vinblastine","Velban","anticancer/mitotic inibitor/plant alkaloid",
"vincristine","Oncovin","anticancer/mitotic inibitor/plant alkaloid",
"vitamin A and D, topical","A & D","emollient/protectant",
"vitamin A and D, topical","Desitin c ZnO","emollient/protectant",
"ziprasidone","Geodon","atypical (2) antipsychotic");

var ron1_len=301;
var ron1_cur=0;
var ron1_word=ron1_steps[0],ron1_target=ron1_steps[2];
var ron1_other=7;
var ron1_goStart=function(){
	ron1_cur=Math.floor(Math.random()*ron1_len);
	var ron1_choice=document.getElementById("ron1_prompt").selectedIndex,ron1_choice2=document.getElementById("ron1_match").selectedIndex;
	ron1_word=ron1_steps[ron1_choice+ron1_cur*3];
	ron1_target=ron1_steps[ron1_choice2+ron1_cur*3];
	var ron1_hit=Math.floor(Math.random()*ron1_other);
	var ron1_res="<strong>"+ron1_word+"</strong><br/>";
	for(var ron1_i=0; ron1_i<ron1_other; ron1_i++){
		if(ron1_i==ron1_hit){
			ron1_res+="<button onclick=\"ron1_goStart();\">"+ron1_target+"</button><br/>";
		}else{
			var ron1_ot=ron1_steps[ron1_choice2+Math.floor(Math.random()*ron1_len)*3];
			while(ron1_ot==ron1_target){
				ron1_ot=ron1_steps[ron1_choice2+Math.floor(Math.random()*ron1_len)*3];
			}
			ron1_res+="<button onclick=\"this.disabled='disabled'\">"+ron1_ot+"</button><br/>";
		}
	}
	document.getElementById("ron1_box").innerHTML=ron1_res;
};