var ftri_steps=new Array("benzocaine<br/><strong>Lanacaine &reg;</strong><br/>antipruritic/antihistamine",
"benzocaine<br/><strong>Americaine &reg;</strong><br/>antipruritic/antihistamine",
"benzocaine<br/><strong>Orajel &reg;</strong><br/>antipruritic/antihistamine",
"dibucaine<br/><strong>Nupercainal &reg;</strong><br/>antipruritic/antihistamine",
"diphenhydramine<br/><strong>Benadryl &reg;</strong><br/>antipruritic/antihistamine",
"cortisol<br/><strong>Cortaid &reg;</strong><br/>antipruritic/corticosteroid",
"desoximetasone<br/><strong>Topicort &reg;</strong><br/>antipruritic/corticosteroid",
"fluocinonide<br/><strong>Lidex &reg;</strong><br/>antipruritic/corticosteroid",
"triamcinolone<br/><strong>Kenalog &reg;</strong><br/>antipruritic/corticosteroid",
"fluocinolone acetonide<br/><strong>Synalar &reg;</strong><br/>antipruritic/corticosteroid",
"vitamin A and D, topical<br/><strong>A & D &reg;</strong><br/>emollient/protectant",
"vitamin A and D, topical<br/><strong>Desitin c ZnO &reg;</strong><br/>emollient/protectant",
"coal tar<br/><strong>Balnetar &reg;</strong><br/>keratolytic",
"coal tar<br/><strong>Polytar &reg;</strong><br/>keratolytic",
"coal tar<br/><strong>Neutrogena T/Gel &reg;</strong><br/>keratolytic",
"salicylic acid<br/><strong>Neutrogena &reg;</strong><br/>acne",
"salicylic acid<br/><strong>Clearasil &reg;</strong><br/>keratolytic/acne",
"salicylic acid<br/><strong>Salex &reg;</strong><br/>keratolytic",
"salicylic acid<br/><strong>Compound W &reg;</strong><br/>keratolytic",
"collagenase<br/><strong>Santyl &reg;</strong><br/>enzymatic",
"permethrin<br/><strong>Acticin &reg;</strong><br/>scabicide/pediculicide",
"permethrin<br/><strong>Elimite &reg;</strong><br/>scabicide/pediculicide",
"permethrin<br/><strong>Nix &reg;</strong><br/>scabicide/pediculicide",
"permethrin<br/><strong>A-200 &reg;</strong><br/>scabicide/pediculicide",
"permethrin<br/><strong>RID &reg;</strong><br/>scabicide/pediculicide",
"lindane<br/><strong>lindane &reg;</strong><br/>scabicide/pediculicide",
"pyrethrins<br/><strong>RID &reg;</strong><br/>scabicide/pediculicide",
"pyrethrins<br/><strong>A-200 &reg;</strong><br/>scabicide/pediculicide",
"terbinafine<br/><strong>Lamisil, AT &reg;</strong><br/>antifungal",
"terbinafine<br/><strong>Mycelex &reg;</strong><br/>antifungal",
"clotrimazole<br/><strong>Lotrimin, Gyne- &reg;</strong><br/>antifungal",
"ketoconazole<br/><strong>Nizoral &reg;</strong><br/>antifungal",
"miconazole<br/><strong>Monistat &reg;</strong><br/>antifungal",
"miconazole<br/><strong>Lotrimin AF &reg;</strong><br/>antifungal",
"nystatin<br/><strong>Mycostatin &reg;</strong><br/>antifungal",
"tolnaftate<br/><strong>Tinactin &reg;</strong><br/>antifungal",
"acyclovir<br/><strong>Zovirax &reg;</strong><br/>antiviral",
"valacyclovir<br/><strong>Valtrex &reg;</strong><br/>antiviral",
"mupirocin<br/><strong>Bactroban &reg;</strong><br/>antibacterial",
"chlorhexidine<br/><strong>Hibiclens &reg;</strong><br/>topical anti-infective/antiseptic",
"chlorhexidine<br/><strong>Peridex &reg;</strong><br/>topical anti-infective/antiseptic",
"povidone-iodine<br/><strong>Betadine &reg;</strong><br/>topical anti-infective/antiseptic",
"silver sulfadiazine<br/><strong>Silvadene &reg;</strong><br/>burn",
"mafenide<br/><strong>Sulfamylon &reg;</strong><br/>burn",
"benzoyl peroxide<br/><strong>Benzac &reg;</strong><br/>acne",
"benzoyl peroxide<br/><strong>Desquam-X &reg;</strong><br/>acne",
"benzoyl peroxide<br/><strong>Panoxyl-5 and 10 &reg;</strong><br/>acne",
"isotretinoin<br/><strong>Sotret &reg;</strong><br/>acne",
"methotrexate<br/><strong>Rheumatrex &reg;</strong><br/>anticancer/antimetabolite",
"fluorouracil<br/><strong>Efudex &reg;</strong><br/>anticancer/antimetabolite",
"cisplatin<br/><strong>Platinol &reg;</strong><br/>anticancer/alkylating agent",
"cyclophosphamide<br/><strong>Cytoxan &reg;</strong><br/>anticancer/alkylating agent",
"vinblastine<br/><strong>Velban &reg;</strong><br/>anticancer/mitotic inibitor/plant alkaloid",
"vincristine<br/><strong>Oncovin &reg;</strong><br/>anticancer/mitotic inibitor/plant alkaloid",
"paclitaxel<br/><strong>Taxol &reg;</strong><br/>anticancer/mitotic inibitor/taxane",
"doxorubicin<br/><strong>Adriamycin &reg;</strong><br/>anticancer/antitumor antibiotic",
"bleomycin<br/><strong>Blenoxane &reg;</strong><br/>anticancer/antitumor antibiotic",
"daunorubicin<br/><strong>Cerubidne &reg;</strong><br/>anticancer/antitumor antibiotic",
"mitomycin<br/><strong>Mutamycin &reg;</strong><br/>anticancer/antitumor antibiotic",
"prednisone<br/><strong>Deltasone &reg;</strong><br/>anticancer/corticosteroid/glucocorticoid",
"dexamethasone<br/><strong>Decadron &reg;</strong><br/>anticancer/corticosteroid",
"tamoxifen<br/><strong>Nolvadex &reg;</strong><br/>anticancer/anti-estrogen",
"anastrozole<br/><strong>Arimidex &reg;</strong><br/>anticancer/anti-estrogen",
"leuprolide acetate<br/><strong>Lupron Depot &reg;</strong><br/>anticancer/anti-androgen",
"bicalutamide<br/><strong>Casodex &reg;</strong><br/>anticancer/anti-androgen",
"interferon alfa<br/><strong>Intron A &reg;</strong><br/>anticancer/interferon",
"interferon alfa<br/><strong>Roferon B &reg;</strong><br/>anticancer/interferon",
"bevacizumab<br/><strong>Avastin &reg;</strong><br/>anticancer/MAB",
"trastuzumab<br/><strong>Herceptin &reg;</strong><br/>anticancer/MAB",
"tositumomab<br/><strong>Bexxar &reg;</strong><br/>anticancer/radioactive isotope",
"epinephrine<br/><strong>Adrenalin &reg;</strong><br/>adrenergic",
"epinephrine<br/><strong>EpiPen, Jr &reg;</strong><br/>adrenergic",
"ephedrine<br/><strong>ephedrine &reg;</strong><br/>adrenergic",
"dopamine<br/><strong>dopamine &reg;</strong><br/>adrenergic",
"isoproterenol<br/><strong>Isuprel &reg;</strong><br/>adrenergic",
"norepinephrine<br/><strong>Levophed &reg;</strong><br/>adrenergic",
"phenylephrine<br/><strong>Neo-Synephrine &reg;</strong><br/>adrenergic",
"propranolol<br/><strong>Inderal &reg;</strong><br/>anti-adrenergic",
"bethanechol<br/><strong>Urecholine &reg;</strong><br/>cholinergic",
"neostigmine<br/><strong>Prostigmin &reg;</strong><br/>cholinergic",
"pilocarpine<br/><strong>Isopto Carpine &reg;</strong><br/>cholinergic",
"atropine<br/><strong>atropine &reg;</strong><br/>anti-cholinergic",
"glycopyrrolate<br/><strong>Robinul &reg;</strong><br/>anti-cholinergic",
"propantheline<br/><strong>Pro-Banthine &reg;</strong><br/>anti-cholinergic",
"scopolamine<br/><strong>Transderm Scop &reg;</strong><br/>anti-emetic/anti-cholinergic",
"homatropine<br/><strong>Isopto Homatropine &reg;</strong><br/>anti-cholinergic",
"caffeine citrate<br/><strong>Cafcit &reg;</strong><br/>stimulant",
"amphetamine<br/><strong>Adderall, XR &reg;</strong><br/>ADHD stimulant",
"lisdexamfetamine<br/><strong>Vyvanse &reg;</strong><br/>ADHD stimulant",
"methylphenidate<br/><strong>Ritalin, SR, LA &reg;</strong><br/>narcolepsy/ADHD stimulant",
"methylphenidate<br/><strong>Concerta &reg;</strong><br/>narcolepsy/ADHD stimulant",
"methylphenidate<br/><strong>Daytrana Patch &reg;</strong><br/>narcolepsy/ADHD stimulant",
"methylphenidate<br/><strong>Metadate ER &reg;</strong><br/>ADHD, senile apathy, refractory depression stimulant",
"modafinil<br/><strong>Provigil &reg;</strong><br/>narcolepsy, sleep apnea, shift-work sleep disorder stimulant",
"atomoxetine<br/><strong>Strattera &reg;</strong><br/>noncontrolled ADHD nonstimulant",
"amitriptyline<br/><strong>Elavil &reg;</strong><br/>antidepressant/tricyclic",
"desipramine<br/><strong>Norpramin &reg;</strong><br/>antidepressant/tricyclic",
"doxepin<br/><strong>Sinequan &reg;</strong><br/>antidepressant/tricyclic",
"imipramine<br/><strong>Tofranil &reg;</strong><br/>antidepressant/tricyclic",
"nortriptyline<br/><strong>Pamelor &reg;</strong><br/>antidepressant/tricyclic",
"isocarboxazid<br/><strong>Marplan &reg;</strong><br/>antidepressant/MAOI",
"phenelzine<br/><strong>Nardil &reg;</strong><br/>antidepressant/MAOI",
"tranylcypromine<br/><strong>Parnate &reg;</strong><br/>antidepressant/MAOI",
"citalopram<br/><strong>Celexa &reg;</strong><br/>antidepressant/SSRI",
"escitalopram<br/><strong>Lexapro &reg;</strong><br/>antidepressant/SSRI",
"fluoxetine<br/><strong>Prozac &reg;</strong><br/>antidepressant/SSRI",
"paroxetine<br/><strong>Paxil, CR &reg;</strong><br/>antidepressant/SSRI",
"sertraline<br/><strong>Zoloft &reg;</strong><br/>antidepressant/SSRI",
"desvenlafaxine<br/><strong>Pristiq &reg;</strong><br/>antidepressant/SNRI",
"duloxetine<br/><strong>Cymbalta &reg;</strong><br/>antidepressant/SNRI",
"venlafaxine<br/><strong>Effexor, XR &reg;</strong><br/>antidepressant/SNRI",
"bupropion<br/><strong>Wellbutrin, SR, XL &reg;</strong><br/>antidepressant/heterocyclic",
"mirtazapine<br/><strong>Remeron &reg;</strong><br/>antidepressant/heterocyclic",
"trazodone<br/><strong>Desyrel &reg;</strong><br/>antidepressant/heterocyclic",
"lithium<br/><strong>Lithobid &reg;</strong><br/>antimanic",
"lithium<br/><strong>Eskalith &reg;</strong><br/>antimanic",
"carbamazepine<br/><strong>Tegretol, XR &reg;</strong><br/>antimanic",
"valproate<br/><strong>Depakote, Depakene, ER &reg;</strong><br/>antimanic",
"olanzpine/fluoxetine<br/><strong>Symbyax &reg;</strong><br/>antimanic/bipolar depression",
"alprazolam<br/><strong>Xanax, XR &reg;</strong><br/>ST anti-anxiety/benzodiazepine",
"chlordiazepoxide<br/><strong>Librium &reg;</strong><br/>ST anti-anxiety/benzodiazepine",
"clorazepate<br/><strong>Tranxene &reg;</strong><br/>ST anti-anxiety/benzodiazepine",
"diazepam<br/><strong>Valium &reg;</strong><br/>ST anti-anxiety/benzodiazepine/C4 skeletal muscle relaxant",
"diazepam<br/><strong>Diastat &reg;</strong><br/>ST anti-anxiety/benzodiazepine/C4 skeletal muscle relaxant",
"lorazepam<br/><strong>Ativan &reg;</strong><br/>ST anti-anxiety/benzodiazepine",
"midazolam<br/><strong>Versed &reg;</strong><br/>ST anti-anxiety/benzodiazepine",
"oxazepam<br/><strong>Serax &reg;</strong><br/>ST anti-anxiety/benzodiazepine",
"buspirone<br/><strong>Buspar &reg;</strong><br/>anti-anxiety",
"hydroxyzine<br/><strong>Vistaril &reg;</strong><br/>anti-anxiety",
"chlorpromazine<br/><strong>Thorazine &reg;</strong><br/>typical (1) antipsychotic/phenothiazine",
"fluphenazine<br/><strong>Prolixin &reg;</strong><br/>typical (1) antipsychotic/phenothiazine",
"perphenazine<br/><strong>Trilafon &reg;</strong><br/>typical (1) antipsychotic/phenothiazine",
"prochlorperazine<br/><strong>Compazine &reg;</strong><br/>typical (1) antipsychotic/phenothiazine/anti-emetic/antidopaminergic",
"thioridazine<br/><strong>Mellaril &reg;</strong><br/>typical (1) antipsychotic/phenothiazine",
"trifluoperazine<br/><strong>Stelazine &reg;</strong><br/>typical (1) antipsychotic/phenothiazine",
"haloperidol<br/><strong>Haldol, decanoate IM &reg;</strong><br/>typical (1) antipsychotic/tranquilizer",
"thiothixene<br/><strong>Navane &reg;</strong><br/>typical (1) antipsychotic",
"aripiprazole<br/><strong>Abilify &reg;</strong><br/>atypical (2) antipsychotic",
"clozapine<br/><strong>Clozaril &reg;</strong><br/>atypical (2) antipsychotic",
"clozapine<br/><strong>Fazaclo ODT &reg;</strong><br/>atypical (2) antipsychotic",
"olanzpine<br/><strong>Zyprexa, -Zydis &reg;</strong><br/>atypical (2) antipsychotic",
"paliperidone<br/><strong>Invega &reg;</strong><br/>atypical (2) antipsychotic",
"quetiapine<br/><strong>Seroquel, XR &reg;</strong><br/>atypical (2) antipsychotic",
"risperidone<br/><strong>Risperdal &reg;</strong><br/>atypical (2) antipsychotic",
"risperidone<br/><strong>Consta &reg;</strong><br/>atypical (2) antipsychotic",
"ziprasidone<br/><strong>Geodon &reg;</strong><br/>atypical (2) antipsychotic",
"indapamide<br/><strong>Lozol &reg;</strong><br/>thiazide diuretic",
"hydrochlorothiazide<br/><strong>Microzide &reg;</strong><br/>thiazide diuretic",
"metolazone<br/><strong>Zaroxolyn &reg;</strong><br/>thiazide diuretic",
"furosemide<br/><strong>Lasix &reg;</strong><br/>loop diuretic",
"bumetanide<br/><strong>Bumex &reg;</strong><br/>loop diuretic",
"torsemide<br/><strong>Demadex &reg;</strong><br/>loop diuretic",
"spironolactone<br/><strong>Aldactone &reg;</strong><br/>K-sparing diuretic",
"triamterene<br/><strong>Dyrenium &reg;</strong><br/>K-sparing diuretic",
"spironolactone/hydrochlorothiazide<br/><strong>Aldactazide &reg;</strong><br/>K-sparing thiazide diuretic",
"triamterene/hydrochlorothiazide<br/><strong>Dyazide, Maxzide &reg;</strong><br/>K-sparing thiazide diuretic",
"mannitol<br/><strong>Osmitrol &reg;</strong><br/>osmotic diuretic",
"probenecid<br/><strong>Benemid &reg;</strong><br/>uricosuric agent",
"allopurinol<br/><strong>Zyloprim &reg;</strong><br/>antigout",
"tolterodine<br/><strong>Detrol, LA &reg;</strong><br/>antispasmodic",
"oxybutynin<br/><strong>Ditropan, XL &reg;</strong><br/>antispasmodic",
"oxybutynin<br/><strong>Oxytrol patch &reg;</strong><br/>antispasmodic",
"darifenacin<br/><strong>Enablex &reg;</strong><br/>antispasmodic",
"solifenacin<br/><strong>VESIcare &reg;</strong><br/>antispasmodic",
"hyoscyamine<br/><strong>Cystospaz &reg;</strong><br/>antispasmodic",
"hyoscyamine<br/><strong>Levsin &reg;</strong><br/>antispasmodic",
"bethanechol<br/><strong>Urecholine &reg;</strong><br/>cholinergic",
"phenazopyridine<br/><strong>Pyridium &reg;</strong><br/>UTI analgesic",
"phenazopyridine<br/><strong>Azo Standard &reg;</strong><br/>UTI analgesic",
"finasteride<br/><strong>Proscar &reg;</strong><br/>BPH anti-androgen",
"dutasteride<br/><strong>Avodart &reg;</strong><br/>BPH anti-androgen",
"doxazosin<br/><strong>Cardura &reg;</strong><br/>BPH alpha-blocker",
"tamsulosin<br/><strong>Flomax &reg;</strong><br/>BPH alpha-blocker",
"terazosin<br/><strong>Hytrin &reg;</strong><br/>BPH alpha-blocker",
"calcium carbonate<br/><strong>Tums &reg;</strong><br/>antacid",
"Al-Mg-simethicone<br/><strong>Maalox &reg;</strong><br/>antacid",
"Al-Mg-simethicone<br/><strong>Gelusil &reg;</strong><br/>antacid",
"Al-Mg-simethicone<br/><strong>Mylanta &reg;</strong><br/>antacid",
"aluminum hydroxide gel<br/><strong>AlternaGel &reg;</strong><br/>antacid",
"cimetidine<br/><strong>Tagamet &reg;</strong><br/>histamine 2 blocker",
"famotidine<br/><strong>Pepcid &reg;</strong><br/>histamine 2 blocker",
"ranitidine<br/><strong>Zantac &reg;</strong><br/>histamine 2 blocker",
"lansoprazole<br/><strong>Prevacid &reg;</strong><br/>PPI ac",
"rabeprazole<br/><strong>Aciphex &reg;</strong><br/>PPI",
"pantoprazole<br/><strong>Protonix &reg;</strong><br/>PPI",
"esomeprazole<br/><strong>Nexium &reg;</strong><br/>PPI ac",
"omeprazole<br/><strong>Prilosec &reg;</strong><br/>PPI ac",
"misoprostol<br/><strong>Cytotec &reg;</strong><br/>gastric mucosal agent with food",
"sucralfate<br/><strong>Carafate &reg;</strong><br/>gastric mucosal agent",
"dicyclomine<br/><strong>Bentyl &reg;</strong><br/>antispasmodic/anticholinergic",
"mesalamine<br/><strong>Asacol &reg;</strong><br/>salicylates",
"mesalamine<br/><strong>Rowasa &reg;</strong><br/>salicylates",
"sulfasalazine<br/><strong>Azulfidine &reg;</strong><br/>salicylates",
"prednisone<br/><strong>Deltasone &reg;</strong><br/>anticancer/corticosteroid/glucocorticoid",
"prednisolone<br/><strong>Medrol &reg;</strong><br/>glucocorticoid",
"hydrocortisone<br/><strong>Cortel &reg;</strong><br/>glucocorticoid",
"bismuth subsalicylate<br/><strong>Kaopectate &reg;</strong><br/>antidiarrheal",
"bismuth subsalicylate<br/><strong>Pepto-Bismol &reg;</strong><br/>antidiarrheal",
"diphenoxylate/atropine<br/><strong>Lomotil &reg;</strong><br/>antidiarrheal/anticholinergic",
"loperamide<br/><strong>Imodium &reg;</strong><br/>antidiarrheal",
"lactobacillus acidophilus<br/><strong>Lactinex &reg;</strong><br/>antidiarrheal/probiotic",
"saccharomyces boulardii<br/><strong>Florastor &reg;</strong><br/>antidiarrheal/probiotic",
"simethicone<br/><strong>Mylicon &reg;</strong><br/>antiflatulent",
"psyllium<br/><strong>Metamucil &reg;</strong><br/>bulk-forming laxative",
"psyllium<br/><strong>Konsyl-D &reg;</strong><br/>bulk-forming laxative",
"psyllium<br/><strong>Hyrocil &reg;</strong><br/>bulk-forming laxative",
"docusate<br/><strong>Colace &reg;</strong><br/>laxative/stool softener",
"mineral oil<br/><strong>Fleet Mineral Oil &reg;</strong><br/>laxative/emollient",
"magnesium hydroxide<br/><strong>Milk of Magnesia &reg;</strong><br/>saline laxative",
"senna<br/><strong>Senokot &reg;</strong><br/>stimulant laxative",
"senna/docusate<br/><strong>Peri-Colace &reg;</strong><br/>stimulant laxative",
"senna/docusate<br/><strong>Senokot-S &reg;</strong><br/>stimulant laxative",
"bisacodyl<br/><strong>Dulcolax &reg;</strong><br/>stimulant laxative",
"bisacodyl<br/><strong>Fleet &reg;</strong><br/>stimulant laxative",
"glycerine<br/><strong>Colace suppository &reg;</strong><br/>osmotic laxative",
"lactulose<br/><strong>Enulose &reg;</strong><br/>osmotic laxative",
"polyethylene glycol<br/><strong>Miralax &reg;</strong><br/>osmotic laxative",
"sorbitol<br/><strong>sorbitol &reg;</strong><br/>osmotic laxative",
"lubiprostone<br/><strong>Amitiza &reg;</strong><br/>laxative/chloride channel activator",
"dimenhydrinate<br/><strong>Dramamine &reg;</strong><br/>anti-emetic/anti-cholinergic",
"meclizine<br/><strong>Antivert &reg;</strong><br/>anti-emetic/anti-cholinergic",
"scopolamine<br/><strong>Transderm-Scop &reg;</strong><br/>anti-emetic/anti-cholinergic",
"metoclopramide<br/><strong>Reglan &reg;</strong><br/>anti-emetic/antidopaminergic",
"prochlorperazine<br/><strong>Compazine &reg;</strong><br/>typical (1) antipsychotic/phenothiazine/anti-emetic/antidopaminergic",
"promethazine<br/><strong>Phenergan &reg;</strong><br/>anti-emetic/antidopaminergic",
"dolasetron<br/><strong>Anzemet &reg;</strong><br/>anti-emetic/serotonin receptor antagonist",
"ondansetron<br/><strong>Zofran &reg;</strong><br/>anti-emetic/serotonin receptor antagonist",
"fluorometholone<br/><strong>FML &reg;</strong><br/>anti-inflammation/corticosteroid",
"prednisolone<br/><strong>Omnipred &reg;</strong><br/>anti-inflammation/corticosteroid",
"prednisolone<br/><strong>Pred Forte &reg;</strong><br/>anti-inflammation/corticosteroid",
"dexamethasone<br/><strong>Maxidex &reg;</strong><br/>NSAID",
"flurbiprofen<br/><strong>Ocufen &reg;</strong><br/>NSAID",
"ketorolac<br/><strong>Acular, LS &reg;</strong><br/>NSAID",
"cyclosporine<br/><strong>Restasis &reg;</strong><br/>anti-inflammation/immunologic agent",
"acetazolamide<br/><strong>Diamox &reg;</strong><br/>antiglaucoma/carbonic anhydrase inhibitor",
"dorzolamide<br/><strong>Trusopt &reg;</strong><br/>antiglaucoma/carbonic anhydrase inhibitor",
"pilocarpine HCl<br/><strong>Isopto Carpine &reg;</strong><br/>antiglaucoma/miotic",
"pilocarpine gel<br/><strong>Pilopine HS &reg;</strong><br/>antiglaucoma/miotic",
"timolol<br/><strong>Timoptic, XE &reg;</strong><br/>antiglaucoma/beta-adrenergic blocker",
"timolol c dorzolamide<br/><strong>Cosopt &reg;</strong><br/>antiglaucoma/beta-adrenergic blocker",
"betaxolol<br/><strong>Betoptic-S &reg;</strong><br/>antiglaucoma/beta-adrenergic blocker",
"brimonidine<br/><strong>Alphagan-P &reg;</strong><br/>antiglaucoma/alpha agonist",
"latanoprost<br/><strong>Xalatan &reg;</strong><br/>antiglaucoma/prostaglandin analog",
"travoprost<br/><strong>Travatan, -Z &reg;</strong><br/>antiglaucoma/prostaglandin analog",
"atropine<br/><strong>Isopto Atropine &reg;</strong><br/>mydriatic",
"cyclopentolate<br/><strong>Cyclogyl &reg;</strong><br/>mydriatic",
"phenylephrine<br/><strong>AK-Dilate &reg;</strong><br/>mydriatic",
"tetracaine<br/><strong>TetraVisc &reg;</strong><br/>local anesthetic",
"proparacaine<br/><strong>Alcaine &reg;</strong><br/>local anesthetic",
"diazepam<br/><strong>Valium &reg;</strong><br/>ST anti-anxiety/benzodiazepine/C4 skeletal muscle relaxant",
"baclofen<br/><strong>Lioresal &reg;</strong><br/>skeletal muscle relaxant",
"carisoprodol<br/><strong>Soma &reg;</strong><br/>C4 skeletal muscle relaxant",
"cyclobenzaprine<br/><strong>Flexeril &reg;</strong><br/>skeletal muscle relaxant",
"dantrolene<br/><strong>Dantrium &reg;</strong><br/>skeletal muscle relaxant",
"methocarbamol<br/><strong>Robaxin &reg;</strong><br/>skeletal muscle relaxant",
"tizanidine<br/><strong>Zanaflex &reg;</strong><br/>skeletal muscle relaxant",
"sulindac<br/><strong>Clinoril &reg;</strong><br/>nonselective/traditional NSAID",
"diclofenac<br/><strong>Voltaren DR, XR &reg;</strong><br/>nonselective/traditional NSAID",
"ibuprofen<br/><strong>Motrin &reg;</strong><br/>nonselective/traditional NSAID",
"ibuprofen<br/><strong>Advil (OTC) &reg;</strong><br/>nonselective/traditional NSAID",
"indomethacin<br/><strong>Indocin, SR &reg;</strong><br/>nonselective/traditional NSAID",
"ketorolac<br/><strong>Toradol &reg;</strong><br/>nonselective/traditional NSAID",
"naproxen<br/><strong>Naprosyn &reg;</strong><br/>nonselective/traditional NSAID",
"naproxen<br/><strong>Anaprox &reg;</strong><br/>nonselective/traditional NSAID",
"naproxen<br/><strong>Aleve (OTC) &reg;</strong><br/>nonselective/traditional NSAID",
"oxaprozin<br/><strong>Daypro &reg;</strong><br/>nonselective/traditional NSAID",
"etodolac<br/><strong>Lodine &reg;</strong><br/>partially selective NSAID",
"meloxicam<br/><strong>Mobic &reg;</strong><br/>partially selective NSAID",
"nabumetone<br/><strong>Relafen &reg;</strong><br/>partially selective NSAID",
"celecoxib<br/><strong>Celebrex &reg;</strong><br/>selective COX-2 inhibitor",
"diclofenac/misoprostol<br/><strong>Arthrotec 50, 75 &reg;</strong><br/>antispasmodic",
"colchicine<br/><strong>Colcrys &reg;</strong><br/>antigout",
"raloxifene<br/><strong>Evista &reg;</strong><br/>anti-osteoporosis/estrogen-R modifier",
"calcitonin-salmon<br/><strong>Miacalcin &reg;</strong><br/>anti-osteoporosis",
"teriparatide<br/><strong>Forteo &reg;</strong><br/>anti-osteoporosis/parathyroid hormone",
"alendronate<br/><strong>Fosamax &reg;</strong><br/>anti-osteoporosis/bisphosphonates",
"ibandronate<br/><strong>Boniva &reg;</strong><br/>anti-osteoporosis/bisphosphonates",
"risedronate<br/><strong>Actonel &reg;</strong><br/>anti-osteoporosis/bisphosphonates",
"carbamazepine<br/><strong>Tegretol, XR &reg;</strong><br/>anticonvulsant (1)",
"clonazepam<br/><strong>Klonopin &reg;</strong><br/>anticonvulsant (1)",
"fosphenytonin<br/><strong>Cerebyx &reg;</strong><br/>anticonvulsant (1)",
"phenytoin<br/><strong>Dilantin &reg;</strong><br/>anticonvulsant (1)",
"ethosuximide<br/><strong>Zarontin &reg;</strong><br/>anticonvulsant (1)",
"valproic acid<br/><strong>Depakene, Depakote DR, ER, Depacon &reg;</strong><br/>anticonvulsant (1)",
"gabapentin<br/><strong>Neurontin &reg;</strong><br/>anticonvulsant (2)",
"pregabalin<br/><strong>Lyrica &reg;</strong><br/>anticonvulsant (2)",
"lamotrigine<br/><strong>Lamictal &reg;</strong><br/>anticonvulsant (2)",
"levetriacetam<br/><strong>Keppra &reg;</strong><br/>anticonvulsant (2)",
"topiramate<br/><strong>Topamax &reg;</strong><br/>anticonvulsant (2)",
"carbidopa and levodopa<br/><strong>Sinemet, CR &reg;</strong><br/>parkinson's/dopamine replacement",
"carbidopa and levodopa<br/><strong>Parcopa &reg;</strong><br/>parkinson's/dopamine replacement",
"bromocriptine<br/><strong>Parlodel &reg;</strong><br/>parkinson's/dopamine agonist",
"pramipexole<br/><strong>Mirapex &reg;</strong><br/>parkinson's/dopamine agonist",
"ropinirole<br/><strong>Requip &reg;</strong><br/>parkinson's/dopamine agonist",
"benztropine<br/><strong>Cogentin &reg;</strong><br/>parkinson's/anticholinergic",
"trihexyphenidyl<br/><strong>Artane &reg;</strong><br/>parkinson's/anticholinergic",
"entacapone<br/><strong>Comtan &reg;</strong><br/>parkinson's/COMT inhibitor",
"entacapone c carbidopa/levodopa<br/><strong>Stalevo &reg;</strong><br/>parkinson's/COMT inhibitor",
"rasagiline<br/><strong>Azilect &reg;</strong><br/>parkinson's/MAOB inhibitor",
"selegiline<br/><strong>Eldepryl &reg;</strong><br/>parkinson's/MAOB inhibitor",
"selegiline<br/><strong>Zelapar &reg;</strong><br/>parkinson's/MAOB inhibitor",
"amantadine<br/><strong>Symmetrel &reg;</strong><br/>parkinson's/antiviral",
"donepezil<br/><strong>Aricept, ODT &reg;</strong><br/>alzheimer's/cholinesterase inhibitor",
"rivastigmine<br/><strong>Exelon &reg;</strong><br/>alzheimer's/cholinesterase inhibitor",
"tacrine<br/><strong>Cognex &reg;</strong><br/>alzheimer's/cholinesterase inhibitor",
"galantamine<br/><strong>Razadyne, ER &reg;</strong><br/>alzheimer's/cholinesterase inhibitor",
"memantine<br/><strong>Namenda &reg;</strong><br/>alzheimer's/NMDA-R antagonist");

var ftri_len=301;
var ftri_cur=0;
var ftri_goStart=function(){
	if(document.getElementById("ftri_Rand").checked) ftri_cur=Math.floor(Math.random()*ftri_len);
	else if(ftri_cur==ftri_len-1) ftri_cur=0;
	else ftri_cur++;

	document.getElementById("ftri_box").innerHTML=ftri_steps[ftri_cur];
};